### ISSUE TITLE
Authentication Failed - You do not have permissions to access the service

### ISSUE THREAD

**Issue by Ashu** [gangverk/LastFm#13]
I just tried the demo and I get this error:

Error Domain=LastFmServiceErrorDomain Code=4 "Authentication Failed - You do not have permissions to access the service" UserInfo={NSLocalizedDescription=Authentication Failed - You do not have permissions to access the service, method=auth.getMobileSession}

What am I doing wrong?

**Comment by kevinrenskers** [comment]
The API key used in the example app is probably no longer valid. Try to run it with your own key.

**Comment by Ashu** [comment]
I used my own keys. But I keep getting the same error.

**Comment by kevinrenskers** [comment]
I see you removed your comment and closed the ticket. Can you explain the problem/fix for future people with the same problem? Thanks!

**Comment by Ashu** [comment]
It was a problem from my side. There was a mistake in API secret key given to me. Your code works perfectly! Thanks.
